name: CI

on:
  pull_request:
  push:
    branches: ['master']
  schedule:
  - cron: '00 01 * * *'

jobs:
  test:
    name: test
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Npm Install
      run: npm ci
    - run: npx playwright install --with-deps
    - name: Build app
      run: npm run build
    - name: Test rust crate
      run: 'wasm-pack test --node'
      working-directory: './crate'
    - name: Run Tests
      run: npm test
    - run: npm run lint
